# Generated by Django 4.0 on 2021-12-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='이름', max_length=10)),
                ('id', models.CharField(help_text='학번', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('EMAIL', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('major', models.CharField(choices=[('CS', '컴퓨터학부'), ('GM', '글로벌미디어학부')], default='CS', max_length=4)),
                ('hintanswer', models.CharField(default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
